export const bangladeshiBanks = [
  "AB Bank PLC",
  "Agrani Bank PLC",
  "Al-Arafah Islami Bank PLC",
  "Bangladesh Commerce Bank Limited",
  "Bangladesh Development Bank PLC",
  "Bangladesh Krishi Bank",
  "Bank Al-Falah Limited",
  "Bank Asia PLC",
  "BASIC Bank Limited",
  "Bengal Commercial Bank PLC",
  "BRAC Bank PLC",
  "Citibank N.A",
  "Citizens Bank PLC",
  "City Bank PLC",
  "Commercial Bank of Ceylon Limited",
  "Community Bank Bangladesh PLC",
  "Dhaka Bank PLC",
  "Dutch-Bangla Bank PLC",
  "Eastern Bank PLC",
  "EXIM Bank PLC",
  "First Security Islami Bank PLC",
  "Global Islami Bank PLC",
  "Habib Bank Ltd.",
  "ICB Islamic Bank Ltd.",
  "IFIC Bank PLC",
  "Islami Bank Bangladesh PLC",
  "Jamuna Bank PLC",
  "Janata Bank PLC",
  "Meghna Bank PLC",
  "Mercantile Bank PLC",
  "Midland Bank Limited",
  "Modhumoti Bank PLC",
  "Mutual Trust Bank PLC",
  "National Bank Limited",
  "National Bank of Pakistan",
  "National Credit & Commerce Bank PLC",
  "NRB Bank Limited",
  "NRBC Bank PLC",
  "One Bank PLC",
  "Padma Bank PLC",
  "Prime Bank PLC",
  "Probashi Kollyan Bank",
  "Pubali Bank PLC",
  "Rajshahi Krishi Unnayan Bank",
  "Rupali Bank PLC",
  "SBAC Bank PLC",
  "Shahjalal Islami Bank PLC",
  "Shimanto Bank PLC",
  "Social Islami Bank PLC",
  "Sonali Bank PLC",
  "Southeast Bank PLC",
  "Standard Bank PLC",
  "Standard Chartered Bank",
  "State Bank of India",
  "The Hong Kong and Shanghai Banking Corporation. Ltd.",
  "The Premier Bank PLC",
  "Trust Bank Limited",
  "Union Bank PLC",
  "United Commercial Bank PLC",
  "Uttara Bank PLC",
  "Woori Bank",
];

export const mobileBankingProviders = [
  "bKash",
  "Nagad",
  "Rocket",
  "SureCash",
  "UPay",
];

export // Mock transaction history data
const transactions = [
  {
    date: "May 1, 2024",
    type: "Payment",
    description: "Payment BLVS00386451 of Royalties for Q1 2024",
    operations: "-1 948.32 €",
    balance: "0.00 €",
  },
  {
    date: "Mar 31, 2024",
    type: "Royalties",
    description: "Q1 2024",
    operations: "1 948.32 €",
    balance: "1 948.32 €",
  },
  {
    date: "Feb 1, 2024",
    type: "Payment",
    description: "Payment BLVS00375113 of Royalties for Q4 2023",
    operations: "-2 255.48 €",
    balance: "0.00 €",
  },
  {
    date: "Feb 1, 2024",
    type: "Payment",
    description: "Payment BLVS00375113 of Royalties for Q4 2023",
    operations: "-2 255.48 €",
    balance: "0.00 €",
  },
  {
    date: "Feb 1, 2024",
    type: "Payment",
    description: "Payment BLVS00375113 of Royalties for Q4 2023",
    operations: "-2 255.48 €",
    balance: "0.00 €",
  },
  {
    date: "Feb 1, 2024",
    type: "Payment",
    description: "Payment BLVS00375113 of Royalties for Q4 2023",
    operations: "-2 255.48 €",
    balance: "0.00 €",
  },
  {
    date: "Feb 1, 2024",
    type: "Payment",
    description: "Payment BLVS00375113 of Royalties for Q4 2023",
    operations: "-2 255.48 €",
    balance: "0.00 €",
  },
  {
    date: "Feb 1, 2024",
    type: "Payment",
    description: "Payment BLVS00375113 of Royalties for Q4 2023",
    operations: "-2 255.48 €",
    balance: "0.00 €",
  },
  {
    date: "Feb 1, 2024",
    type: "Payment",
    description: "Payment BLVS00375113 of Royalties for Q4 2023",
    operations: "-2 255.48 €",
    balance: "0.00 €",
  },
  // More mock data entries
];
export const rows = [
  {
    id: 1,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Daga Dili Mone",
    artist: "Samiya Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "05/28/2024",
    upc: "3617388805843",
    catNo: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "20 stores",
  },
  {
    id: 2,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Kar Buke Bandhili Ghor",
    artist: "Shimul Hasan",
    label: "Popy Multimedia",
    releaseDate: "05/06/2024",
    upc: "3617387828485",
    catNo: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "17 stores",
  },
  {
    id: 3,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Tomar Name Nalish Dimu Khodar Dorbare",
    artist: "Larjina Parbin",
    label: "Popy Multimedia",
    releaseDate: "04/26/2024",
    upc: "3617387467752",
    catNo: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "20 stores",
  },
  {
    id: 4,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Tor Moto Beiman Jogote Nai",
    artist: "Samiya Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "04/19/2024",
    upc: "3617387151392",
    catNo: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
  {
    id: 5,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "O Kolijar Pakhi",
    artist: "Larjina Parbin",
    label: "Popy Multimedia",
    releaseDate: "04/08/2024",
    upc: "3617386633707",
    catNo: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
  {
    id: 6,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Ami Sesh Nabir Ummat",
    artist: "Moni Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "03/28/2024",
    upc: "3617386173661",
    catNo: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "20 stores",
  },
  {
    id: 7,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Roja Rakho Namaj Poro",
    artist: "Moni Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "03/17/2024",
    upc: "3617385691500",
    catNo: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
  {
    id: 8,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Roja Rakho Namaj Poro",
    artist: "Moni Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "03/17/2024",
    upc: "3617385691500",
    catNo: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
  {
    id: 9,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Roja Rakho Namaj Poro",
    artist: "Moni Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "03/17/2024",
    upc: "3617385691500",
    catNo: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
  {
    id: 10,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Roja Rakho Namaj Poro",
    artist: "Moni Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "03/17/2024",
    upc: "3617385691500",
    catNo: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
  {
    id: 11,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Roja Rakho Namaj Poro",
    artist: "Moni Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "03/17/2024",
    upc: "3617385691500",
    catNo: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
  {
    id: 12,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Roja Rakho Namaj Poro",
    artist: "Moni Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "03/17/2024",
    upc: "3617385691500",
    catNo: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
  {
    id: 13,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Roja Rakho Namaj Poro",
    artist: "Moni Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "03/17/2024",
    upc: "3617385691500",
    catNo: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
  {
    id: 14,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Roja Rakho Namaj Poro",
    artist: "Moni Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "03/17/2024",
    upc: "3617385691500",
    catNo: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
  {
    id: 15,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Roja Rakho Namaj Poro",
    artist: "Moni Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "03/17/2024",
    upc: "3617385691500",
    catNo: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
];
