export const bangladeshiBanks = [
  "AB Bank PLC",
  "Agrani Bank PLC",
  "Al-Arafah Islami Bank PLC",
  "Bangladesh Commerce Bank Limited",
  "Bangladesh Development Bank PLC",
  "Bangladesh Krishi Bank",
  "Bank Al-Falah Limited",
  "Bank Asia PLC",
  "BASIC Bank Limited",
  "Bengal Commercial Bank PLC",
  "BRAC Bank PLC",
  "Citibank N.A",
  "Citizens Bank PLC",
  "City Bank PLC",
  "Commercial Bank of Ceylon Limited",
  "Community Bank Bangladesh PLC",
  "Dhaka Bank PLC",
  "Dutch-Bangla Bank PLC",
  "Eastern Bank PLC",
  "EXIM Bank PLC",
  "First Security Islami Bank PLC",
  "Global Islami Bank PLC",
  "Habib Bank Ltd.",
  "ICB Islamic Bank Ltd.",
  "IFIC Bank PLC",
  "Islami Bank Bangladesh PLC",
  "Jamuna Bank PLC",
  "Janata Bank PLC",
  "Meghna Bank PLC",
  "Mercantile Bank PLC",
  "Midland Bank Limited",
  "Modhumoti Bank PLC",
  "Mutual Trust Bank PLC",
  "National Bank Limited",
  "National Bank of Pakistan",
  "National Credit & Commerce Bank PLC",
  "NRB Bank Limited",
  "NRBC Bank PLC",
  "One Bank PLC",
  "Padma Bank PLC",
  "Prime Bank PLC",
  "Probashi Kollyan Bank",
  "Pubali Bank PLC",
  "Rajshahi Krishi Unnayan Bank",
  "Rupali Bank PLC",
  "SBAC Bank PLC",
  "Shahjalal Islami Bank PLC",
  "Shimanto Bank PLC",
  "Social Islami Bank PLC",
  "Sonali Bank PLC",
  "Southeast Bank PLC",
  "Standard Bank PLC",
  "Standard Chartered Bank",
  "State Bank of India",
  "The Hong Kong and Shanghai Banking Corporation. Ltd.",
  "The Premier Bank PLC",
  "Trust Bank Limited",
  "Union Bank PLC",
  "United Commercial Bank PLC",
  "Uttara Bank PLC",
  "Woori Bank",
];

export const mobileBankingProviders = [
  "bKash",
  "Nagad",
  "Rocket",
  "SureCash",
  "UPay",
];

export // Mock transaction history data
const transactions = [
  {
    date: "May 1, 2024",
    type: "Payment",
    description: "Payment BLVS00386451 of Royalties for Q1 2024",
    operations: "-1 948.32 $",
    balance: "0.00 $",
  },
  {
    date: "Mar 31, 2024",
    type: "Royalties",
    description: "Q1 2024",
    operations: "1 948.32 $",
    balance: "1 948.32 $",
  },
  {
    date: "Feb 1, 2024",
    type: "Payment",
    description: "Payment BLVS00375113 of Royalties for Q4 2023",
    operations: "-2 255.48 $",
    balance: "0.00 $",
  },
  {
    date: "Feb 1, 2024",
    type: "Payment",
    description: "Payment BLVS00375113 of Royalties for Q4 2023",
    operations: "-2 255.48 $",
    balance: "0.00 $",
  },
  {
    date: "Feb 1, 2024",
    type: "Payment",
    description: "Payment BLVS00375113 of Royalties for Q4 2023",
    operations: "-2 255.48 $",
    balance: "0.00 $",
  },
  {
    date: "Feb 1, 2024",
    type: "Payment",
    description: "Payment BLVS00375113 of Royalties for Q4 2023",
    operations: "-2 255.48 $",
    balance: "0.00 $",
  },
  {
    date: "Feb 1, 2024",
    type: "Payment",
    description: "Payment BLVS00375113 of Royalties for Q4 2023",
    operations: "-2 255.48 $",
    balance: "0.00 $",
  },
  {
    date: "Feb 1, 2024",
    type: "Payment",
    description: "Payment BLVS00375113 of Royalties for Q4 2023",
    operations: "-2 255.48 $",
    balance: "0.00 $",
  },
  {
    date: "Feb 1, 2024",
    type: "Payment",
    description: "Payment BLVS00375113 of Royalties for Q4 2023",
    operations: "-2 255.48 $",
    balance: "0.00 $",
  },
  // More mock data entries
];
export const rows = [
  {
    id: 1,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Daga Dili Mone",
    artist: "Samiya Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "05/28/2024",
    upc: "3617388805843",
    isrc: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "20 stores",
  },
  {
    id: 2,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Kar Buke Bandhili Ghor",
    artist: "Shimul Hasan",
    label: "Popy Multimedia",
    releaseDate: "05/06/2024",
    upc: "3617387828485",
    isrc: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "17 stores",
  },
  {
    id: 3,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Tomar Name Nalish Dimu Khodar Dorbare",
    artist: "Larjina Parbin",
    label: "Popy Multimedia",
    releaseDate: "04/26/2024",
    upc: "3617387467752",
    isrc: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "20 stores",
  },
  {
    id: 4,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Tor Moto Beiman Jogote Nai",
    artist: "Samiya Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "04/19/2024",
    upc: "3617387151392",
    isrc: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
  {
    id: 5,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "O Kolijar Pakhi",
    artist: "Larjina Parbin",
    label: "Popy Multimedia",
    releaseDate: "04/08/2024",
    upc: "3617386633707",
    isrc: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
  {
    id: 6,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Ami Sesh Nabir Ummat",
    artist: "Moni Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "03/28/2024",
    upc: "3617386173661",
    isrc: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "20 stores",
  },
  {
    id: 7,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Roja Rakho Namaj Poro",
    artist: "Moni Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "03/17/2024",
    upc: "3617385691500",
    isrc: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
  {
    id: 8,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Roja Rakho Namaj Poro",
    artist: "Moni Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "03/17/2024",
    upc: "3617385691500",
    isrc: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
  {
    id: 9,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Roja Rakho Namaj Poro",
    artist: "Moni Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "03/17/2024",
    upc: "3617385691500",
    isrc: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
  {
    id: 10,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Roja Rakho Namaj Poro",
    artist: "Moni Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "03/17/2024",
    upc: "3617385691500",
    isrc: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
  {
    id: 11,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Roja Rakho Namaj Poro",
    artist: "Moni Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "03/17/2024",
    upc: "3617385691500",
    isrc: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
  {
    id: 12,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Roja Rakho Namaj Poro",
    artist: "Moni Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "03/17/2024",
    upc: "3617385691500",
    isrc: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
  {
    id: 13,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Roja Rakho Namaj Poro",
    artist: "Moni Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "03/17/2024",
    upc: "3617385691500",
    isrc: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
  {
    id: 14,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Roja Rakho Namaj Poro",
    artist: "Moni Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "03/17/2024",
    upc: "3617385691500",
    isrc: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
  {
    id: 15,
    cover:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    title: "Roja Rakho Namaj Poro",
    artist: "Moni Chowdhury",
    label: "Popy Multimedia",
    releaseDate: "03/17/2024",
    upc: "3617385691500",
    isrc: "empty",
    tracks: "1 Track",
    promote: "",
    territories: "240 terrs.",
    stores: "21 stores",
  },
];
export const videosData = [
  {
    image:
      "https://img.freepik.com/premium-psd/jazz-concert-banner-template_23-2149016105.jpg?w=1380",
    name: "Video Name",
    createdBy: "jeancolc lasa",
    label: "Taranga Electro center Jun 24,2024",
    catalogNumber: "Cat#:TEC3001 744662925003 Release Id:416651",
    stores: "220 terrs, 21 Stored",
  },
  {
    image:
      "https://img.freepik.com/free-psd/music-concert-facebook-template_23-2149959353.jpg?w=1380&t=st=1717396042~exp=1717396642~hmac=3ed5b19d91dde372cbc75905a981b538a87285dca11a523ffec316eb090d4050",
    name: "Video Name",
    createdBy: "jeancolc lasa",
    label: "Taranga Electro center Jun 24,2024",
    catalogNumber: "Cat#:TEC3001 744662925003 Release Id:416651",
    stores: "220 terrs, 21 Stored",
  },
  {
    image:
      "https://img.freepik.com/premium-psd/feel-music-event-banner-template-design-psd_394216-16.jpg?w=1380",
    name: "Video Name",
    createdBy: "jeancolc lasa",
    label: "Taranga Electro center Jun 24,2024",
    catalogNumber: "Cat#:TEC3001 744662925003 Release Id:416651",
    stores: "220 terrs, 21 Stored",
  },
  {
    image:
      "https://img.freepik.com/free-psd/music-festival-banner-template_23-2148911140.jpg?w=1380&t=st=1717396073~exp=1717396673~hmac=55f764269162dd468ebb21ef39305a74f8d061ae5eb180f9d22c0d061e28fcd4",
    name: "Video Name",
    createdBy: "jeancolc lasa",
    label: "Taranga Electro center Jun 24,2024",
    catalogNumber: "Cat#:TEC3001 744662925003 Release Id:416651",
    stores: "220 terrs, 21 Stored",
  },
];
export const services = [
  {
    icon: (
      <img
        className="w-[35px] h-[35px] ml-[75px]"
        src="https://img.freepik.com/premium-vector/set-tiktok-app-icons-social-media-logo-vector-illustration_277909-592.jpg"
        alt="TikTok"
      />
    ),
    title: "TikTok Manual Claim",
    type: "tiktok",
  },
  {
    icon: (
      <img
        className="w-w-[35px] h-[35px] ml-[95px]"
        src="https://upload.wikimedia.org/wikipedia/commons/c/cd/Facebook_logo_%28square%29.png"
        alt="Facebook"
      />
    ),
    title: "Facebook Claim Release",
    type: "facebook",
  },
  {
    icon: (
      <img
        className="w-[60px] h-[40px] ml-[75px]"
        src="https://e7.pngegg.com/pngimages/125/937/png-clipart-youtube-logo-youtube-angle-logo-thumbnail.png"
        alt="YouTube"
      />
    ),
    title: "YouTube Claim Release",
    type: "youtube",
  },
  {
    icon: (
      <img
        className="w-[60px] h-[40px] ml-[85px]"
        src="https://e7.pngegg.com/pngimages/125/937/png-clipart-youtube-logo-youtube-angle-logo-thumbnail.png"
        alt="YouTube Takedown"
      />
    ),
    title: "YouTube Video Takedowns Request",
    type: "youtube-takedown",
  },
  {
    icon: (
      <img
        className="w-[60px] h-[40px] ml-[75px]"
        src="https://e7.pngegg.com/pngimages/125/937/png-clipart-youtube-logo-youtube-angle-logo-thumbnail.png"
        alt="YouTube Manual Claim"
      />
    ),
    title: "YouTube Manual UGC Claim",
    type: "youtube-manual",
  },
  {
    icon: (
      <img
        className="w-w-[35px] h-[35px] ml-[95px]"
        src="https://upload.wikimedia.org/wikipedia/commons/c/cd/Facebook_logo_%28square%29.png"
        alt="Facebook Whitelist"
      />
    ),
    title: "Facebook Page Whitelist",
    type: "facebook-whitelist",
  },
  {
    icon: (
      <img
        className="w-[60px] h-[40px] ml-[75px]"
        src="https://e7.pngegg.com/pngimages/125/937/png-clipart-youtube-logo-youtube-angle-logo-thumbnail.png"
        alt="Artist Channel"
      />
    ),
    title: "Artist Channel Request",
    type: "artist-channel-request",
  },
  {
    icon: (
      <img
        className="w-[60px] h-[40px] ml-[60px]"
        src="https://e7.pngegg.com/pngimages/125/937/png-clipart-youtube-logo-youtube-angle-logo-thumbnail.png"
        alt="Whitelist Request"
      />
    ),
    title: "WhiteListRequest",
    type: "white-list-request",
  },
];
export // Mock Data
const releaseInformationData = {
  tracks: {
    contentType: "Audio",
    primaryTrackType: "Music",
    secondaryTrackType: "Original",
    instrumental: "No",
    title: "Sample Track",
    remixer: "Sample Remixer",
    author: "Sample Author",
    composer: "Sample Composer",
    arranger: "Sample Arranger",
    producer: "Sample Producer",
    pLine: "Sample ℗ Line",
    productionYear: "2023",
    publisher: "Sample Publisher",
    isrc: "Sample ISRC",
    askToGenerateIsrc: "No",
    price: "10.99",
    producerCatalogueNumber: "Sample Catalogue Number",
    parentalAdvisory: "No",
    previewStart: "00:00",
    trackTitleLanguage: "English",
    lyricsLanguage: "English",
    lyrics: "Sample Lyrics",
  },
  release: {
    releaseTitle: "Sample Release",
    versionSubtitle: "Sample Version",
    primaryArtists: ["Sample Artist 1"],
    featuringArtists: ["Sample Artist 2"],
    variousArtistsCompilation: false,
    genre: "Rock",
    subgenre: "Classic Rock",
    labelName: "Sample Label",
    format: "CD",
    physicalReleaseDate: "2023-01-01",
    pLine: "Sample Ⓟ Line",
    cLine: "Sample © Line",
    productionYear: "2023",
    upcEan: "Sample UPC/EAN",
    producerCatalogueNumber: "Sample Catalogue Number",
  },
  audio: {
    coverImage:
      "https://static.vecteezy.com/system/resources/thumbnails/000/435/728/small/1404.i033.096.S.m003.c10.Headphones_grunge.jpg",
    audioFile: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
  },
};
export const genres = [
  {
    name: "African",
    subgenres: [
      "African",
      "African- Afrikaans",
      "African- Afro Bashment",
      "African- Afro Pop",
      "African- Afro Soul",
      "African- Afro Trap",
      "African- Afro Urban",
      "African- Afrobeat",
      "African- Assiko",
      "African- Bend-Skin",
      "African- Benga",
      "African- Bikutsi",
      "African- Bango-flava",
      "African- Coupe Decale",
      "African- Gospel",
      "African- Gqom",
      "African- Highlife/ Hiplife",
      "African- Juju Music",
      "African- Kizomba",
    ],
  },
  {
    name: "Indian",
    subgenres: [
      "Indian",
      "Indian - Assamese",
      "Indian - Assamese Soundtrack",
      "Indian - Bengali",
      "Indian - Bengali Soundtrack",
      "Indian - Bhangra",
      "Indian - Bhojpuri",
      "Indian - Bhojpuri Soundtrack",
      "Indian - Bollywood",
      "Indian - Carnatic Classical",
      "Indian - Carnatic Classical Instrumental",
      "Indian - Children Song",
      "Indian - Classical",
      "Indian - Classical / Instrumental",
      "Indian - Classical / Vocal",
      "Indian - Devotional & Spiritual",
      "Indian - Dialogue",
      "Indian - DJ",
      "Indian - Folk",
      "Indian - Fusion",
      "Indian - Gazal",
      "Indian - Gujarati",
      "Indian - Gujarati Soundtrack",
      "Indian - Haryanvi",
      "Indian - Haryanvi Soundtrack",
      "Indian - Hindi",
      "Indian - Hindi Non Soundtrack",
      "Indian - Hindi Soundtrack",
      "Indian - Hindustani Classical",
      "Indian - Hindustani Classical Instrumental",
      "Indian - Indigenous",
      "Indian - Kannada",
      "Indian - Kannada Soundtrack",
      "Indian - Konkani",
      "Indian - Malayalam",
      "Indian - Malayalam Soundtrack",
      "Indian - Mappila",
      "Indian - Marathi",
      "Indian - Marathi Soundtrack",
      "Indian - Odia",
      "Indian - Odia Soundtrack",
      "Indian - Poetry",
      "Indian - Pop & Fusion",
      "Indian - Punjabi",
      "Indian - Punjabi Soundtrack",
      "Indian - Rabindra sangeet",
      "Indian - Rajasthani",
      "Indian - Rajasthani Soundtrack",
      "Indian - Regional Indian",
      "Indian - Regional Indian Soundtrack",
      "Indian - Sanskrit",
      "Indian - Sanskrit Soundtrack",
      "Indian - Speech",
      "Indian - Sufi",
      "Indian - Tamil",
      "Indian - Tamil Soundtrack",
      "Indian - Telugu",
      "Indian - Telugu Soundtrack",
      "Indian - Traditional",
      "Indian - Urdu",
      "Indian - Urdu Soundtrack",
    ],
  },
  {
    name: "Alternative",
    subgenres: [
      "Alternative",
      "Alternative- Electronic / EBM",
      "Alternative- Emo Punk",
      "Alternative- Gothic",
      "Alternative- Grunge",
      "Alternative- Indie Pop",
      "Alternative- Indie Rock",
      "Alternative- Latin",
      "Alternative- Latin Ska",
      "Alternative- New Wave",
      "Alternative- Pop Punk",
      "Alternative- Post Punk",
      "Alternative- Punk",
      "Alternative- Ska",
    ],
  },
  {
    name: "Arabic",
    subgenres: [
      "Arabic",
      "Arabic- Algerian Rai",
      "Arabic- Amazigh",
      "Arabic- Arabesque",
      "Arabic- Egyptian Chaabiat",
      "Arabic- Egyptian Folk Ei Kaf Aswain",
      "Arabic- Egyptian Folk Nubian",
      "Arabic- Egyptian Folk Saidi",
      "Arabic- Egyptian Indie",
      "Arabic- Egyptian Mahraganat",
      "Arabic- Egyptian Musicals",
      "Arabic- Egyptian Operette",
      "Arabic- Egyptian Patriotic",
      "Arabic- Egyptian Plays",
      "Arabic- Egyptian Satire",
      "Arabic- Egyptian Soundtrack",
      "Arabic- Egyptian Tarab Classical",
      "Arabic- Egyptian Tarab Pop",
      "Arabic- Egyptian TV Shows",
      "Arabic- Electronic Dance Music",
      "Arabic- Indie",
      "Arabic- Iraqi Folk Dabka",
      "Arabic- Iraqi Folk Khachaba",
      "Arabic- Iraqi Folk Maqam",
      "Arabic- Iraqi Folk Mawaweel",
      "Arabic- Iraqi Folk Radeh",
      "Arabic- Iraqi Indie",
      "Arabic- Iraqi Musicals",
      "Arabic- Iraqi Operette",
      "Arabic- Iraqi Patriotic",
      "Arabic- Iraqi Plays",
      "Arabic- Iraqi Satire",
      "Arabic- Iraqi Soundtrack",
      "Arabic- Iraqi Tarab Classical",
      "Arabic- Iraqi Tarab Pop",
      "Arabic- Iraqi TV Shows",
      "Arabic- Iraqi Islamic",
      "Arabic- Islamic Anasheed",
      "Arabic- Islamic Chant",
      "Arabic- Islamic Quran",
      "Arabic- Islamic Ramadan",
      "Arabic- Islamic Recital",
      "Arabic- Islamic Speeches",
      "Arabic- Khaleeji",
      "Arabic- Khaleeji Folk Shakashaka",
      "Arabic- Khaleeji Folk Swahili",
      "Arabic- Khaleeji Indie",
      "Arabic- Khaleeji Musicals",
      "Arabic- Khaleeji Operette",
      "Arabic- Khaleeji Patriotic",
      "Arabic- Khaleeji Plays",
      "Arabic- Khaleeji Satire",
      "Arabic- Khaleeji Shayla",
      "Arabic- Khaleeji Soundtrack",
      "Arabic- Khaleeji Tarab Classical",
      "Arabic- Khaleeji Tarab Pop",
      "Arabic- Khaleeji TV Shows",
      "Arabic- Kurdish",
      "Arabic- Lebanese Folk Ataba & Mijana",
      "Arabic- Lebanese Folk Dabke",
      "Arabic- Lebanese Folk Zajal",
      "Arabic- Lebanese Indie",
      "Arabic- Lebanese Musicals",
      "Arabic- Lebanese Operette",
      "Arabic- Lebanese Patriotic",
      "Arabic- Lebanese Plays",
      "Arabic- Lebanese Satire",
      "Arabic- Lebanese Soundtrack",
      "Arabic- Lebanese Tarab Classical",
      "Arabic- Lebanese Tarab Pop",
      "Arabic- Lebanese TV Shows",
      "Arabic- Levantine Folk Bedouin",
      "Arabic- Levantine Folk New Dabke Syrian",
      "Arabic- Levantine Folk Qoudud & Muwashahat",
      "Arabic- Levantine Indie",
      "Arabic- Levantine Musicals",
      "Arabic- Levantine Operette",
      "Arabic- Levantine Patriotic",
      "Arabic- Levantine Plays",
      "Arabic- Levantine Satire",
      "Arabic- Levantine Soundtrack",
      "Arabic- Levantine Tarab Classical",
      "Arabic- Levantine Tarab Pop",
      "Arabic- Levantine TV Shows",
      "Arabic- Maalaya Folk Dagni",
      "Arabic- Moroccan Rai",
      "Arabic- Moroccan Sahraaoui",
      "Arabic- North African",
      "Arabic- North African Folk Andalusi",
      "Arabic- North African Folk Gnawa",
      "Arabic- North African Folk Mezwed",
      "Arabic- North African Folk Rif",
      "Arabic- North African Indie",
      "Arabic- North African Musicals",
      "Arabic- North African Operette",
      "Arabic- North African Patriotic",
      "Arabic- North African Plays",
      "Arabic- North African Rai Classical",
      "Arabic- North African Satire",
      "Arabic- North African Soundtrack",
      "Arabic- North African Tarab Classical",
      "Arabic- North African Tarab Pop",
      "Arabic- North African TV Shows",
      "Arabic- Rai",
      "Arabic- Sufi",
      "Arabic- Sudanese Folk Swahili",
      "Arabic- Sudanese Indie",
      "Arabic- Sudanese Musicals",
      "Arabic- Sudanese Operette",
      "Arabic- Sudanese Patriotic",
      "Arabic- Sudanese Plays",
      "Arabic- Sudanese Satire",
      "Arabic- Sudanese Soundtrack",
      "Arabic- Sudanese Tarab Classical",
      "Arabic- Sudanese Tarab Pop",
      "Arabic- Sudanese TV Shows",
      "Arabic- Yemeni Folk Hadramawti",
      "Arabic- Yemeni Folk Swahili",
      "Arabic- Yemeni Indie",
      "Arabic- Yemeni Musicals",
      "Arabic- Yemeni Operette",
      "Arabic- Yemeni Patriotic",
      "Arabic- Yemeni Plays",
      "Arabic- Yemeni Satire",
      "Arabic- Yemeni Soundtrack",
      "Arabic- Yemeni Tarab Classical",
      "Arabic- Yemeni Tarab Pop",
      "Arabic- Yemeni TV Shows",
    ],
  },
  {
    name: "Asian",
    subgenres: [
      "Asian",
      "Asian- Chinese",
      "Asian- Chinese / Tibetan Native",
      "Asian- Chinese Folk",
      "Asian- Filipino / Bikol",
      "Asian- Filipino / Cebuano",
      "Asian- Filipino / Chavacano",
      "Asian- Filipino / llocano",
      "Asian- Filipino / Kapampoangan",
      "Asian- Filipino / llonggo",
      "Asian- Filipino / Pangasinan",
      "Asian- Filipino / Tagalog",
      "Asian- Filipino / Waray",
      "Asian- Hong Kongese",
      "Asian- Indonesian",
      "Asian- Indonesian / Christian Pop",
      "Asian- Indonesian / Keroncong",
      "Asian- Indonesian / Koplo",
      "Asian- Indonesian / Religious",
      "Asian- Japanese",
      "Asian- Korean",
      "Asian- Malaysian",
      "Asian- Malaysian / Chinese New Year",
      "Asian- Malaysian / Christmas",
      "Asian- Malaysian / Deepavali",
      "Asian- Malaysian / Hari Raya",
      "Asian- Malaysian / Traditional",
      "Asian- OPM / 70'S Pinoy Music",
      "Asian- OPM / 80'S Pinoy Music",
      "Asian- OPM / 90'S Pinoy Music",
      "Asian- OPM / BisRock",
      "Asian- OPM / Cebuano",
      "Asian- OPM / Chavacano",
      "Asian- OPM / Folk Songs / Country Music",
      "Asian- OPM / Harana & Kundiman",
      "Asian- OPM / Hiligaynon",
      "Asian- OPM / llocano",
      "Asian- OPM / Kapampangan",
      "Asian- OPM / Pinoy Acoustic",
      "Asian- OPM / Pinoy Ballad",
      "Asian- OPM / Pinoy Love Songs",
      "Asian- Pinoy Rock",
      "Asian- Taiwanese",
      "Asian- Taiwanese Folk",
      "Asian- Thai",
      "Asian- Thai / Folk Music",
      "Asian- Thai / Luk-Krung",
      "Asian- Thai / Luk-Thung",
      "Asian- Thai / Mo-Lam",
      "Asian- Thai / Song For Life",
      "Asian- Vietnamese",
      "Asian- Vietnamese / Bai troi",
      "Asian- Vietnamese / Bolero",
      "Asian- Vietnamese / Ca Tru",
      "Asian- Vietnamese / Cai Luong",
      "Asian- Vietnamese / Cheo",
      "Asian- Vietnamese / Dinh Hue",
      "Asian- Vietnamese / Don Ca Tai Tu",
      "Asian- Vietnamese / Ho Hue",
      "Asian- Vietnamese / Ly",
      "Asian- Vietnamese / Nhac Cung",
      "Asian- Vietnamese / Nhac Ru",
      "Asian- Vietnamese / Tuong",
      "Asian- Vietnamese / Xam",
    ],
  },
  {
    name: "Blues",
    subgenres: [
      "Blues",
      "Blues- Acoustic",
      "Blues- Blues Gospel",
      "Blues- Boogie-Woogie",
      "Blues- Chicago Blues",
      "Blues- Country Blues",
      "Blues- Delta Blues",
      "Blues- Electric",
      "Blues- Harmonica",
      "Blues- Modern Electric Blues",
      "Blues- Piano",
      "Blues- Regional Blues",
      "Blues- Soul",
    ],
  },
  {
    name: "Children's Music",
    subgenres: [
      "Children's Music",
      "Children's Music- Arabic",
      "Children's Music- Christmas",
      "Children's Music- Easter",
      "Children's Music- Halloween",
      "Children's Music- Hanukkah",
      "Children's Music- Music For Children",
    ],
  },
  {
    name: "Christian & Gospel",
    subgenres: [
      "Christian & Gospel",
      "Christian & Gospel- CCM",
      "Christian & Gospel- Christian Dance / DJ",
      "Christian & Gospel- Christian Hymns",
      "Christian & Gospel- Christian Metal",
      "Christian & Gospel- Christian Punk",
      "Christian & Gospel- Christian Rap",
      "Christian & Gospel- Christian Rock",
      "Christian & Gospel- Gospel",
      "Christian & Gospel- Praise & Worship",
      "Christian & Gospel- Southern Gospel",
      "Christian & Gospel- Traditional Gospel",
    ],
  },
  {
    name: "Classical",
    subgenres: [
      "Classical",
      "Classical- Baroque",
      "Classical- Choral",
      "Classical- Early Music",
      "Classical- High Classical",
      "Classical- Impressionist",
      "Classical- Minimalism",
      "Classical- Modern",
      "Classical- Opera",
      "Classical- Orchestral",
      "Classical- Renaissance",
      "Classical- Romantic",
    ],
  },
  {
    name: "Comedy",
    subgenres: ["Comedy", "Novelty", "Parody Music", "Standup Comedy"],
  },
  {
    name: "Country",
    subgenres: [
      "Country",
      "Alternative Country",
      "Americana",
      "Bluegrass",
      "Contemporary Bluegrass",
      "Contemporary Country",
      "Country Gospel",
      "Honky Tonk",
      "Outlaw Country",
      "Traditional Bluegrass",
      "Traditional Country",
      "Urban Cowboy",
    ],
  },
  {
    name: "Dance",
    subgenres: [
      "Dance",
      "Breakbeat",
      "Brostep",
      "Chillstep",
      "Deep House",
      "Disco",
      "Dubstep",
      "Electro House",
      "Electroswing",
      "Exercise",
      "Future House",
      "Garage",
      "Glitch Hop",
      "Hardcore",
      "Hard Dance",
      "Hi-NRG",
      "Horrorcore",
      "Jackin House",
      "Jungle/Drum’n’bass",
      "Liquid Dub",
      "Regstep",
      "Speedcore",
      "Techno",
      "Trance",
      "Trap",
      "Trip Hop",
      "Tropical House",
    ],
  },
  {
    name: "Electronic",
    subgenres: [
      "Electronic",
      "2-Step",
      "Acid House",
      "Ambient",
      "Bassline",
      "Big Beat",
      "Chill Out",
      "Chiptune",
      "Crunk",
      "Dancehall",
      "Darkcore",
      "Deep House",
      "Dub",
      "Downtempo",
      "Drum & Bass",
      "Dubstep",
      "Electro",
      "Electronica",
      "Electro Swing",
      "Eurobeat",
      "Eurodance",
      "Garage",
      "Glitch",
      "Grime",
      "Hardstyle",
      "Hi-NRG",
      "House",
      "IDM",
      "Industrial",
      "Jungle",
      "Liquid Dub",
      "Lo-fi",
      "Minimal",
      "Progressive House",
      "Psytrance",
      "Rave",
      "Synthpop",
      "Tech House",
      "Techno",
      "Trance",
      "UK Garage",
    ],
  },
  {
    name: "Folk",
    subgenres: [
      "Folk",
      "Alternative Folk",
      "Contemporary Folk",
      "Folk Rock",
      "Indie Folk",
      "Traditional Folk",
    ],
  },
  {
    name: "Hip-Hop/Rap",
    subgenres: [
      "Hip-Hop/Rap",
      "Alternative Hip-Hop",
      "Bounce",
      "Dirty South",
      "East Coast Rap",
      "Gangsta Rap",
      "Hardcore Rap",
      "Hip-Hop",
      "Latin Rap",
      "Old School Rap",
      "Rap",
      "Underground Hip-Hop",
      "West Coast Rap",
    ],
  },
  {
    name: "Jazz",
    subgenres: [
      "Jazz",
      "Jazz- Avant Garde",
      "Jazz- Bebop",
      "Jazz- Big Band",
      "Jazz- Blue Note",
      "Jazz- Contemporary Jazz",
      "Jazz- Cool",
      "Jazz- Crossover Jazz",
      "Jazz- Dixieland",
      "Jazz- Ethio-jazz",
      "Jazz- Fusion",
      "Jazz- Gypsy Jazz",
      "Jazz- Hard Bop",
      "Jazz- Latin Jazz",
      "Jazz- Mainstream Jazz",
      "Jazz- Ragtime",
      "Jazz- Smooth Jazz",
      "Jazz- Swing",
      "Jazz- Vocal Jazz",
    ],
  },
  {
    name: "Latin",
    subgenres: [
      "Latin",
      "Latin- Bachata",
      "Latin- Baladas y Boleros",
      "Latin- Brazilian",
      "Latin- Contemporary Latin",
      "Latin- Latin Folk",
      "Latin- Latin Jazz",
      "Latin- Latin Pop",
      "Latin- Latin Rap/Hip-Hop",
      "Latin- Latin Rock",
      "Latin- Merengue",
      "Latin- Nuevo Flamenco",
      "Latin- Pop Rock",
      "Latin- Reggaeton",
      "Latin- Salsa",
      "Latin- Tango",
      "Latin- Tejano",
    ],
  },
  {
    name: "Pop",
    subgenres: [
      "Pop",
      "Pop- Adult Contemporary",
      "Pop- Britpop",
      "Pop- Bubblegum Pop",
      "Pop- Chamber Pop",
      "Pop- Dance Pop",
      "Pop- Dream Pop",
      "Pop- Electro Pop",
      "Pop- Indie Pop",
      "Pop- J-Pop",
      "Pop- K-Pop",
      "Pop- Latin Pop",
      "Pop- Pop Punk",
      "Pop- Pop Rap",
      "Pop- Pop Rock",
      "Pop- Power Pop",
      "Pop- Soft Rock",
      "Pop- Synth-pop",
      "Pop- Teen Pop",
    ],
  },
  {
    name: "Reggae",
    subgenres: [
      "Reggae",
      "Reggae- Dancehall",
      "Reggae- Dub",
      "Reggae- Lovers Rock",
      "Reggae- Ragga",
      "Reggae- Rocksteady",
      "Reggae- Roots Reggae",
      "Reggae- Ska",
      "Reggae- Soca",
    ],
  },
  {
    name: "Rock",
    subgenres: [
      "Rock",
      "Rock- Alternative Rock",
      "Rock- Arena Rock",
      "Rock- Blues Rock",
      "Rock- Classic Rock",
      "Rock- Folk Rock",
      "Rock- Garage Rock",
      "Rock- Glam Rock",
      "Rock- Hard Rock",
      "Rock- Indie Rock",
      "Rock- Math Rock",
      "Rock- Progressive Rock",
      "Rock- Psychedelic Rock",
      "Rock- Punk Rock",
      "Rock- Rock & Roll",
      "Rock- Soft Rock",
      "Rock- Southern Rock",
      "Rock- Stoner Rock",
      "Rock- Surf Rock",
    ],
  },
  {
    name: "Soul",
    subgenres: [
      "Soul",
      "Soul- Contemporary R&B",
      "Soul- Funk",
      "Soul- Motown",
      "Soul- Neo-Soul",
      "Soul- Northern Soul",
      "Soul- Psychedelic Soul",
      "Soul- Quiet Storm",
      "Soul- Southern Soul",
      "Soul- Soul Blues",
    ],
  },
];
export const albumReleaseInformationData = {
  tracks: [
    {
      title: "Mock Song 1",
      version: "Mock Version 1",
      primaryArtists: ["Mock Artist 1", "Artist 2"],
      featuringArtists: ["Mock Featuring Artist 1"],
      writers: ["Mock Writer 1"],
      composers: ["Mock Composer 1"],
      directors: ["Mock Director 1"],
      producers: ["Mock Producer 1"],
      genre: "Mock Genre 1",
      subgenre: "Mock Subgenre 1",
      label: "Mock Label 1",
      format: "Mock Format 1",
      releaseDate: "2022-01-01",
      publisher: "Mock Publisher 1",
      language: "Mock Language 1",
      productionYear: "2022",
      isrc: "Mock ISRC 1",
      youtube: "Mock Youtube URL 1",
      lyrics: "Mock Lyrics 1",
      price: "Mock Price 1",
      producer: "Mock Producer 1",
      remixer: "Mock Remixer 1",
      author: "Mock Author 1",
      arranger: "Mock Arranger 1",
      pLine: "Mock P Line 1",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
      instrumental: "Yes",
      contentType: "Mock Content Type 1",
      primaryTrackType: "Mock Primary Track Type 1",
      parentalAdvisory: "Yes",
      trackTitleLanguage: "English",
      lyricsLanguage: "English",
      previewStart: "0:00",
    },
    {
      title: "Mock Song 2",
      version: "Mock Version 2",
      primaryArtists: ["Mock Artist 2"],
      featuringArtists: ["Mock Featuring Artist 2"],
      writers: ["Mock Writer 2"],
      composers: ["Mock Composer 2"],
      directors: ["Mock Director 2"],
      producers: ["Mock Producer 2"],
      genre: "Mock Genre 2",
      subgenre: "Mock Subgenre 2",
      label: "Mock Label 2",
      format: "Mock Format 2",
      releaseDate: "2022-02-02",
      publisher: "Mock Publisher 2",
      language: "Mock Language 2",
      productionYear: "2023",
      isrc: "Mock ISRC 2",
      youtube: "Mock Youtube URL 2",
      lyrics: "Mock Lyrics 2",
      price: "Mock Price 2",
      producer: "Mock Producer 2",
      remixer: "Mock Remixer 2",
      author: "Mock Author 2",
      arranger: "Mock Arranger 2",
      pLine: "Mock P Line 2",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
      instrumental: "No",
      contentType: "Mock Content Type 2",
      primaryTrackType: "Mock Primary Track Type 2",
      parentalAdvisory: "No",
      trackTitleLanguage: "Spanish",
      lyricsLanguage: "Spanish",
      previewStart: "0:30",
    },
  ],
  release: {
    releaseTitle: "Mock Album Title",
    versionSubtitle: "Mock Version Subtitle",
    primaryArtists: ["Mock Primary Artist"],
    featuringArtists: ["Mock Featuring Artist"],
    variousArtistsCompilation: false,
    genre: "Mock Genre",
    subgenre: "Mock Subgenre",
    labelName: "Mock Label Name",
    format: "Mock Format",
    physicalReleaseDate: "2022-01-01",
    pLine: "Mock P Line",
    cLine: "Mock C Line",
    productionYear: "2022",
    upcEan: "Mock UPC/EAN",
    producerCatalogueNumber: "Mock Producer Catalogue Number",
  },
  audio: {
    coverImage:
      "https://images.pexels.com/photos/1323206/pexels-photo-1323206.jpeg?cs=srgb&dl=pexels-mixu-513809-1323206.jpg&fm=jpg",
  },
};
