export enum tagTypes {
  user = "user",
  admin = "admin",
  coupon = "coupon",
  cover = "cover",
  offer = "offer",
  category = "category",
  policy = "policy",
  about = "about",
  terms = "terms",
  profile = "profile",
  password = "password",
  feedback = "feedback",
  status = "status",
  order = "order",
  product = "product",
  forget = "forget",
  reset = "reset",
  verify = "verify",
  subCategory = "subCategory",
  faq = "faq",
  dashboard = "dashboard",
  notification = "notification",
}

export const tagTypesList = [tagTypes];
